{
  "formatVersion": "1.1",
  "component": {
    "group": "com.franzandel.common.features",
    "module": "common-features",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-features-1.aar",
          "url": "common-features-1.aar",
          "size": 1638,
          "sha512": "7e801f1fb82664f98ec001adf2dfacbac7411c227251d959dad34445b6dad7d4c172e53e395ce63255e69141ae94df0fb3472f663a88b5743a15e65d463e6886",
          "sha256": "1273e9eb43646c8fc31561f491efe58b1b86095cbf7e0a003f5646c7230e4fd8",
          "sha1": "9a1b2b3ab141b279f57a089cecb97b633daf6c96",
          "md5": "00db204aad8e99926f1438ac006b4e48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.franzandel.design.library",
          "module": "design-library",
          "version": {
            "requires": "2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-features-1.aar",
          "url": "common-features-1.aar",
          "size": 1638,
          "sha512": "7e801f1fb82664f98ec001adf2dfacbac7411c227251d959dad34445b6dad7d4c172e53e395ce63255e69141ae94df0fb3472f663a88b5743a15e65d463e6886",
          "sha256": "1273e9eb43646c8fc31561f491efe58b1b86095cbf7e0a003f5646c7230e4fd8",
          "sha1": "9a1b2b3ab141b279f57a089cecb97b633daf6c96",
          "md5": "00db204aad8e99926f1438ac006b4e48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-features-1-sources.jar",
          "url": "common-features-1-sources.jar",
          "size": 1010,
          "sha512": "1b8df54e8e544b356909305b6ccbd2a205a590067696ab64eb70199472657b809affd5a191accbba6c97f5333748ad953cfb2569e6af6ba0444522571efadce5",
          "sha256": "e42dec46f003d68fbf74e48f8b4ad3875a2dec328dee46f198f8a5950f7c392f",
          "sha1": "72ca56280199907db1fa479004940505cc38e185",
          "md5": "eb1c72eabcc74af5cee8c3dc3598845d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-features-1-javadoc.jar",
          "url": "common-features-1-javadoc.jar",
          "size": 260208,
          "sha512": "aaf5a759d46fb959ee4f1b23c2a1528a5c3701667d8ec35668bbddfd67df8b17ea71c9a56485081faa68b759b7e6ee62c862a6f24e2a82633b272ac4d75472ca",
          "sha256": "7561bbc357c6bff8adab8b4553f7e3342672c7ac022e77d63500b5efac3c470f",
          "sha1": "2e7032b036d511063dfabfe33de0a32c27d7704a",
          "md5": "c2be3afe03348b082dbaffc7f03ab567"
        }
      ]
    }
  ]
}
